import type { CategoryKind, FinancialAccountType, DebtType, InvestmentType, GoalType } from "@prisma/client";

export type DefaultCategorySeed = {
  name: string;
  kind: CategoryKind;
  icon: string;
  color: string;
  subcategories?: { name: string; icon: string; color: string }[];
};

export const DEFAULT_CATEGORIES: DefaultCategorySeed[] = [
  {
    name: "Alimentação",
    kind: "EXPENSE",
    icon: "utensils",
    color: "#10B981",
    subcategories: [
      { name: "Mercado", icon: "shopping-cart", color: "#A7F3D0" },
      { name: "Restaurante", icon: "utensils", color: "#6EE7B7" },
      { name: "Lanche", icon: "sandwich", color: "#34D399" },
      { name: "Delivery", icon: "bike", color: "#10B981" },
      { name: "Outros", icon: "shapes", color: "#059669" },
    ],
  },
  {
    name: "Compras",
    kind: "EXPENSE",
    icon: "shopping-bag",
    color: "#F43F5E",
    subcategories: [
      { name: "Roupas", icon: "shirt", color: "#FECDD3" },
      { name: "Calçados", icon: "footprints", color: "#FDA4AF" },
      { name: "Eletrônicos", icon: "laptop", color: "#FB7185" },
      { name: "Casa", icon: "sofa", color: "#F43F5E" },
      { name: "Acessórios", icon: "watch", color: "#BE123C" },
      { name: "Presentes", icon: "gift", color: "#9F1239" },
      { name: "Compras online", icon: "shopping-bag", color: "#881337" },
      { name: "Outros", icon: "shapes", color: "#FFE4E6" },
    ],
  },
  {
    name: "Cuidados pessoais",
    kind: "EXPENSE",
    icon: "sparkles",
    color: "#EC4899",
    subcategories: [
      { name: "Cabeleireiro/Barbearia", icon: "scissors", color: "#FBCFE8" },
      { name: "Manicure/Pedicure", icon: "hand", color: "#F9A8D4" },
      { name: "Cosméticos", icon: "sparkles", color: "#F472B6" },
      { name: "Higiene pessoal", icon: "droplets", color: "#EC4899" },
      { name: "Estética", icon: "gem", color: "#DB2777" },
      { name: "Academia", icon: "dumbbell", color: "#BE185D" },
      { name: "Outros", icon: "shapes", color: "#9D174D" },
    ],
  },
  {
    name: "Educação",
    kind: "EXPENSE",
    icon: "graduation-cap",
    color: "#6366F1",
    subcategories: [
      { name: "Cursos", icon: "book-open", color: "#C7D2FE" },
      { name: "Faculdade/Escola", icon: "graduation-cap", color: "#A5B4FC" },
      { name: "Apostilas", icon: "book", color: "#818CF8" },
      { name: "Material escolar", icon: "pencil", color: "#6366F1" },
      { name: "Cursos online", icon: "monitor", color: "#4F46E5" },
      { name: "Idiomas", icon: "languages", color: "#4338CA" },
      { name: "Certificações", icon: "award", color: "#3730A3" },
      { name: "Outros", icon: "shapes", color: "#312E81" },
    ],
  },
  {
    name: "Entretenimento",
    kind: "EXPENSE",
    icon: "clapperboard",
    color: "#A855F7",
    subcategories: [
      { name: "Cinema", icon: "clapperboard", color: "#E9D5FF" },
      { name: "Streaming", icon: "tv", color: "#D8B4FE" },
      { name: "Música", icon: "music", color: "#C084FC" },
      { name: "Jogos", icon: "gamepad-2", color: "#A855F7" },
      { name: "Eventos/Shows", icon: "ticket", color: "#9333EA" },
      { name: "Teatro", icon: "drama", color: "#7E22CE" },
      { name: "Livros", icon: "book", color: "#6B21A8" },
      { name: "Hobbies", icon: "palette", color: "#581C87" },
      { name: "Assinaturas", icon: "repeat", color: "#86198F" },
      { name: "Outros", icon: "shapes", color: "#3B0764" },
    ],
  },
  {
    name: "Família",
    kind: "EXPENSE",
    icon: "users",
    color: "#14B8A6",
    subcategories: [
      { name: "Filhos", icon: "baby", color: "#99F6E4" },
      { name: "Pensão", icon: "hand-coins", color: "#5EEAD4" },
      { name: "Ajuda familiar", icon: "heart-handshake", color: "#2DD4BF" },
      { name: "Presentes", icon: "gift", color: "#14B8A6" },
      { name: "Mesada", icon: "wallet", color: "#0D9488" },
      { name: "Cuidados com familiares", icon: "heart-pulse", color: "#0F766E" },
      { name: "Outros", icon: "shapes", color: "#115E59" },
    ],
  },
  {
    name: "Finanças",
    kind: "EXPENSE",
    icon: "landmark",
    color: "#8B5CF6",
    subcategories: [
      { name: "Cartão de crédito", icon: "credit-card", color: "#DDD6FE" },
      { name: "Tarifas bancárias", icon: "landmark", color: "#C4B5FD" },
      { name: "Juros", icon: "percent", color: "#A78BFA" },
      { name: "Empréstimos", icon: "hand-coins", color: "#8B5CF6" },
      { name: "Financiamentos", icon: "file-text", color: "#7C3AED" },
      { name: "Impostos/Taxas", icon: "receipt", color: "#6D28D9" },
      { name: "Outros", icon: "shapes", color: "#5B21B6" },
    ],
  },
  {
    name: "Moradia",
    kind: "EXPENSE",
    icon: "home",
    color: "#2563EB",
    subcategories: [
      { name: "Aluguel", icon: "key", color: "#BFDBFE" },
      { name: "Condomínio", icon: "building", color: "#93C5FD" },
      { name: "Energia", icon: "zap", color: "#60A5FA" },
      { name: "Gás", icon: "flame", color: "#3B82F6" },
      { name: "Internet", icon: "wifi", color: "#2563EB" },
      { name: "Água", icon: "droplet", color: "#1D4ED8" },
      { name: "Manutenção/Reparos", icon: "wrench", color: "#1E40AF" },
      { name: "IPTU", icon: "file-text", color: "#1E3A8A" },
      { name: "Outros", icon: "shapes", color: "#172554" },
    ],
  },
  {
    name: "Pets",
    kind: "EXPENSE",
    icon: "paw-print",
    color: "#F97316",
    subcategories: [
      { name: "Ração", icon: "bone", color: "#FED7AA" },
      { name: "Veterinário", icon: "stethoscope", color: "#FDBA74" },
      { name: "Medicamentos", icon: "pill", color: "#FB923C" },
      { name: "Acessórios", icon: "package", color: "#F97316" },
      { name: "Pet Shop", icon: "store", color: "#EA580C" },
      { name: "Banho e Tosa", icon: "scissors", color: "#C2410C" },
      { name: "Outros", icon: "shapes", color: "#9A3412" },
    ],
  },
  {
    name: "Saúde",
    kind: "EXPENSE",
    icon: "heart-pulse",
    color: "#EF4444",
    subcategories: [
      { name: "Plano de saúde", icon: "shield", color: "#FECACA" },
      { name: "Consulta médica", icon: "stethoscope", color: "#FCA5A5" },
      { name: "Exames", icon: "file-text", color: "#F87171" },
      { name: "Farmácia/Medicamentos", icon: "pill", color: "#EF4444" },
      { name: "Outros", icon: "shapes", color: "#DC2626" },
    ],
  },
  {
    name: "Transporte",
    kind: "EXPENSE",
    icon: "car",
    color: "#F59E0B",
    subcategories: [
      { name: "Combustível", icon: "fuel", color: "#FEF3C7" },
      { name: "Transporte público", icon: "bus", color: "#FDE68A" },
      { name: "Uber/99/Táxi", icon: "car", color: "#FCD34D" },
      { name: "Estacionamento", icon: "parking-circle", color: "#FBBF24" },
      { name: "Pedágio", icon: "ticket", color: "#F59E0B" },
      { name: "Manutenção", icon: "wrench", color: "#D97706" },
      { name: "Seguro", icon: "shield", color: "#B45309" },
      { name: "IPVA/Licenciamento", icon: "file-text", color: "#92400E" },
      { name: "Lavagem", icon: "droplet", color: "#78350F" },
      { name: "Financiamento", icon: "landmark", color: "#713F12" },
      { name: "Outros", icon: "shapes", color: "#451A03" },
    ],
  },
  {
    name: "Viagens",
    kind: "EXPENSE",
    icon: "plane",
    color: "#06B6D4",
    subcategories: [
      { name: "Passagens", icon: "ticket", color: "#CFFAFE" },
      { name: "Hospedagem", icon: "bed", color: "#A5F3FC" },
      { name: "Alimentação", icon: "utensils", color: "#67E8F9" },
      { name: "Transporte", icon: "car", color: "#22D3EE" },
      { name: "Passeios e atrações", icon: "map-pin", color: "#06B6D4" },
      { name: "Compras", icon: "shopping-bag", color: "#0891B2" },
      { name: "Bagagem", icon: "luggage", color: "#0E7490" },
      { name: "Seguro viagem", icon: "shield", color: "#155E75" },
      { name: "Documentação", icon: "file-text", color: "#164E63" },
      { name: "Outros", icon: "shapes", color: "#083344" },
    ],
  },
  { name: "Salário", kind: "INCOME", icon: "wallet", color: "#22c55e" },
  { name: "Freelance", kind: "INCOME", icon: "laptop", color: "#16a34a" },
  { name: "Bonificação", kind: "INCOME", icon: "gift", color: "#15803d" },
  { name: "Rendimentos", kind: "INCOME", icon: "trending-up", color: "#059669" },
  { name: "Dividendos", kind: "INCOME", icon: "coins", color: "#0d9488" },
  { name: "Aluguéis", kind: "INCOME", icon: "building-2", color: "#0891b2" },
  { name: "Outras receitas", kind: "INCOME", icon: "plus-circle", color: "#65a30d" },
  { name: "Renda Fixa", kind: "INVESTMENT", icon: "landmark", color: "#0ea5e9" },
  { name: "Renda Variável", kind: "INVESTMENT", icon: "trending-up", color: "#22c55e" },
  { name: "Fundos Imobiliário", kind: "INVESTMENT", icon: "building-2", color: "#a855f7" },
  { name: "Criptomoedas", kind: "INVESTMENT", icon: "bitcoin", color: "#f59e0b" },
  { name: "Exterior", kind: "INVESTMENT", icon: "globe", color: "#06b6d4" },
  { name: "Previdência", kind: "INVESTMENT", icon: "shield", color: "#64748b" },
  { name: "Outros", kind: "INVESTMENT", icon: "shapes", color: "#94a3b8" },
];

export const ACCOUNT_TYPE_LABELS: Record<FinancialAccountType, string> = {
  CHECKING: "Conta corrente",
  SAVINGS: "Poupança",
  DIGITAL_WALLET: "Carteira digital",
  CASH: "Dinheiro em espécie",
  INVESTMENT: "Conta de investimento",
};

export const DEBT_TYPE_LABELS: Record<DebtType, string> = {
  LOAN: "Empréstimo",
  FINANCING: "Financiamento",
  INSTALLMENT: "Parcelamento",
  CREDIT_CARD: "Cartão de crédito",
  OTHER: "Outra dívida",
};

export const INVESTMENT_TYPE_LABELS: Record<InvestmentType, string> = {
  FIXED_INCOME: "Renda fixa",
  STOCK: "Ações",
  ETF: "ETFs",
  FUND: "Fundos",
  CRYPTO: "Criptomoedas",
  PENSION: "Previdência",
  OTHER: "Outros ativos",
};

export const GOAL_TYPE_LABELS: Record<GoalType, string> = {
  EMERGENCY_FUND: "Reserva de emergência",
  TRAVEL: "Viagem",
  HOUSE: "Casa / Imóvel",
  CAR: "Carro / Veículo",
  DEBT_PAYOFF: "Quitar dívidas",
  INVESTMENT: "Investimentos",
  EDUCATION: "Educação",
  SHOPPING: "Compras",
  PERSONAL_EVENT: "Eventos / Projetos pessoais",
  CUSTOM: "Outras",
};

export const CHART_COLORS = [
  "#6366f1",
  "#22c55e",
  "#f59e0b",
  "#ef4444",
  "#06b6d4",
  "#a855f7",
  "#ec4899",
  "#84cc16",
  "#0ea5e9",
  "#f97316",
];
